apiVersion: apps/v1
kind: Deployment
metadata:
  name: appk8s-test2
  namespace: demo-test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appk8s-test2
  template:
    metadata:
      labels:
        app: appk8s-test2
    spec:
      containers:
      - name: appk8s-test2
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80