controller:
  admin:
    username: admin
    password: "dongtran123"

  numExecutors: 0

  serviceType: LoadBalancer
  servicePort: 32090
  targetPort: 8080
  jenkinsUrl: "http://localhost:32090"
  agentListenerServiceType: ClusterIP

  installPlugins:
    - kubernetes:4423.vb_59f230b_ce53
    - workflow-aggregator:608.v67378e9d3db_1
    - workflow-job:1505.vea_4b_20a_4a_495
    - pipeline-model-api:2.2255.v56a_15e805f12
    - pipeline-model-extensions:2.2255.v56a_15e805f12
    - pipeline-model-definition:2.2255.v56a_15e805f12
    - git:5.10.1
    - configuration-as-code:2061.vc08919f7fc37

  installLatestPlugins: false
  initializeOnce: false
  overwritePlugins: true
  overwritePluginsFromImage: true

agent:
  enabled: true
  useDefaultServiceAccount: false
  serviceAccount: jenkins-agent-admin
  podTemplates:
    kubectl: |
      - name: kubectl
        label: kubectl
        serviceAccount: jenkins-agent-admin
        containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            command: "/bin/sh -c"
            args: "sleep 99d"
            ttyEnabled: true

rbac:
  create: true

persistence:
  enabled: true